// frontend/src/components/AgentTopology/index.tsx
import { BadgeCheck, BookOpenText, CircleAlert, Clock3, Send, ShieldCheck } from 'lucide-react'

export type AgentRuntimeStatus = 'waiting' | 'active' | 'done' | 'error'

export interface AgentTopologyStatusMap {
  reader: AgentRuntimeStatus
  reviewer: AgentRuntimeStatus
  dispatcher: AgentRuntimeStatus
}

interface AgentTopologyProps {
  agentsStatus: AgentTopologyStatusMap
}

type AgentKey = keyof AgentTopologyStatusMap

const agentMeta: Record<
  AgentKey,
  {
    title: string
    icon: typeof BookOpenText
    activeGlow: string
    iconTone: string
    subtitle: string
  }
> = {
  reader: {
    title: 'Reader',
    icon: BookOpenText,
    activeGlow: 'bg-blue-500/20',
    iconTone: 'text-blue-100',
    subtitle: 'Document ingestion',
  },
  reviewer: {
    title: 'Reviewer',
    icon: ShieldCheck,
    activeGlow: 'bg-blue-500/20',
    iconTone: 'text-slate-100',
    subtitle: 'Review and critic',
  },
  dispatcher: {
    title: 'Dispatcher',
    icon: Send,
    activeGlow: 'bg-emerald-500/20',
    iconTone: 'text-emerald-100',
    subtitle: 'Dispatch output',
  },
}

function getNodeClass(status: AgentRuntimeStatus) {
  if (status === 'active') {
    return 'agent-node-active border-blue-500 bg-slate-800/85'
  }

  if (status === 'done') {
    return 'border-emerald-500/45 bg-slate-900/70'
  }

  if (status === 'error') {
    return 'border-red-500/45 bg-red-950/25'
  }

  return 'border-slate-700 bg-slate-900/45 opacity-75'
}

function getStatusText(status: AgentRuntimeStatus) {
  if (status === 'active') return 'Processing...'
  if (status === 'done') return 'Completed'
  if (status === 'error') return 'Failed'
  return 'Pending'
}

function getStatusTextClass(status: AgentRuntimeStatus) {
  if (status === 'active') return 'text-blue-400 font-bold animate-pulse'
  if (status === 'done') return 'text-emerald-400'
  if (status === 'error') return 'text-red-400'
  return 'text-slate-500'
}

function getNodeBadge(status: AgentRuntimeStatus) {
  if (status === 'active') return <Clock3 className="h-3.5 w-3.5" />
  if (status === 'done') return <BadgeCheck className="h-3.5 w-3.5" />
  if (status === 'error') return <CircleAlert className="h-3.5 w-3.5" />
  return <Clock3 className="h-3.5 w-3.5" />
}

export default function AgentTopology({ agentsStatus }: AgentTopologyProps) {
  const lineStatus = {
    readerToReviewer: agentsStatus.reader === 'done' && agentsStatus.reviewer === 'waiting',
    reviewerToDispatcher: agentsStatus.reviewer === 'done' && agentsStatus.dispatcher === 'waiting',
  }

  return (
    <div className="relative flex h-full min-h-[230px] w-full select-none items-center justify-center overflow-hidden rounded-[1.6rem] border border-white/8 bg-[linear-gradient(180deg,rgba(2,6,23,0.68),rgba(15,23,42,0.46))] p-6">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(56,189,248,0.14),transparent_28%),radial-gradient(circle_at_bottom_right,rgba(16,185,129,0.12),transparent_24%)]" />

      <svg className="pointer-events-none absolute inset-0 h-full w-full" aria-hidden="true">
        <path d="M 25% 50% L 50% 50%" stroke="#334155" strokeWidth="2" fill="none" strokeDasharray="6 6" />
        {lineStatus.readerToReviewer && (
          <path
            d="M 25% 50% L 50% 50%"
            stroke="#3b82f6"
            strokeWidth="2"
            fill="none"
            strokeDasharray="6 6"
            className="animate-dash"
          />
        )}

        <path d="M 50% 50% L 75% 50%" stroke="#334155" strokeWidth="2" fill="none" strokeDasharray="6 6" />
        {lineStatus.reviewerToDispatcher && (
          <path
            d="M 50% 50% L 75% 50%"
            stroke="#3b82f6"
            strokeWidth="2"
            fill="none"
            strokeDasharray="6 6"
            className="animate-dash"
          />
        )}
      </svg>

      <div className="relative z-10 flex w-full flex-col gap-4 px-2 md:flex-row md:justify-around md:gap-6">
        {(Object.keys(agentMeta) as AgentKey[]).map((agentKey) => {
          const meta = agentMeta[agentKey]
          const status = agentsStatus[agentKey]
          const Icon = meta.icon

          return (
            <div
              key={agentKey}
              className={`agent-topology-node relative flex min-w-0 flex-1 items-center gap-4 rounded-xl border px-5 py-4 transition-all duration-500 ${getNodeClass(status)}`}
            >
              <div className="agent-topology-icon-box flex h-11 w-11 shrink-0 items-center justify-center rounded-lg border border-slate-700 bg-slate-800 shadow-inner">
                <Icon className={`h-5 w-5 ${meta.iconTone}`} />
              </div>

              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-bold tracking-wider text-slate-100">{meta.title}</span>
                  <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] ${getStatusTextClass(status)}`}>
                    {getNodeBadge(status)}
                    {getStatusText(status)}
                  </span>
                </div>
                <p className="mt-2 text-xs uppercase tracking-[0.22em] text-white/35">{meta.subtitle}</p>
              </div>

              {status === 'active' && <div className={`absolute -inset-1 -z-10 rounded-xl blur-md ${meta.activeGlow}`} />}
            </div>
          )
        })}
      </div>
    </div>
  )
}

// frontend/src/components/AgentTopology.vue
<template>
  <div class="w-full h-full flex items-center justify-center relative select-none">
    
    <svg class="absolute inset-0 w-full h-full pointer-events-none" z-index="0">
      <path d="M 25% 50% L 50% 50%" stroke="#334155" stroke-width="2" fill="none" stroke-dasharray="6,6" />
      <path v-if="lineStatus.readerToReviewer" d="M 25% 50% L 50% 50%" stroke="#3b82f6" stroke-width="2" fill="none" stroke-dasharray="6,6" class="animate-dash" />
      
      <path d="M 50% 50% L 75% 50%" stroke="#334155" stroke-width="2" fill="none" stroke-dasharray="6,6" />
      <path v-if="lineStatus.reviewerToCritic" d="M 50% 50% L 75% 50%" stroke="#3b82f6" stroke-width="2" fill="none" stroke-dasharray="6,6" class="animate-dash" />
    </svg>

    <div class="relative z-10 w-full flex justify-around items-center px-8">
      
      <div class="agent-node" :class="getNodeClass('reader')">
        <div class="icon-box bg-slate-800 text-slate-300">📄</div>
        <div class="flex flex-col">
          <span class="font-bold text-slate-200 tracking-wider">Reader</span>
          <span class="text-[10px] uppercase tracking-widest transition-colors duration-300" :class="getStatusTextColor('reader')">
            {{ getStatusText('reader') }}
          </span>
        </div>
        <div v-if="agents.reader === 'active'" class="absolute -inset-1 bg-blue-500/20 blur-md rounded-xl -z-10 animate-pulse"></div>
      </div>

      <div class="agent-node" :class="getNodeClass('reviewer')">
        <div class="icon-box bg-slate-800 text-slate-300">👁️</div>
        <div class="flex flex-col">
          <span class="font-bold text-slate-200 tracking-wider">Reviewer</span>
          <span class="text-[10px] uppercase tracking-widest transition-colors duration-300" :class="getStatusTextColor('reviewer')">
            {{ getStatusText('reviewer') }}
          </span>
        </div>
        <div v-if="agents.reviewer === 'active'" class="absolute -inset-1 bg-blue-500/20 blur-md rounded-xl -z-10 animate-pulse"></div>
      </div>

      <div class="agent-node" :class="getNodeClass('dispatcher')">
        <div class="icon-box bg-slate-800 text-slate-300">⚖️</div>
        <div class="flex flex-col">
          <span class="font-bold text-slate-200 tracking-wider">Dispatcher</span>
          <span class="text-[10px] uppercase tracking-widest transition-colors duration-300" :class="getStatusTextColor('dispatcher')">
            {{ getStatusText('dispatcher') }}
          </span>
        </div>
        <div v-if="agents.dispatcher === 'active'" class="absolute -inset-1 bg-emerald-500/20 blur-md rounded-xl -z-10 animate-pulse"></div>
      </div>

    </div>
  </div>
</template>

<script setup>
import { reactive } from 'vue'

// 节点状态：waiting, active, done, error
const agents = reactive({
  reader: 'waiting',
  reviewer: 'waiting',
  dispatcher: 'waiting'
})

// 连线流动状态
const lineStatus = reactive({
  readerToReviewer: false,
  reviewerToCritic: false
})

// --- 对外暴露的方法：给 App.vue 调用 ---
const setAgentStatus = (agentName, status) => {
  const name = String(agentName || '').toLowerCase()
  if (agents[name] !== undefined) {
    agents[name] = status
    
    // 自动控制连线的流向动画
    if (name === 'reader' && status === 'done') lineStatus.readerToReviewer = true
    if (name === 'reviewer' && status === 'active') lineStatus.readerToReviewer = false
    if (name === 'reviewer' && status === 'done') lineStatus.reviewerToCritic = true
    if (name === 'dispatcher' && status === 'active') lineStatus.reviewerToCritic = false
  }
}

const reset = () => {
  agents.reader = 'waiting'
  agents.reviewer = 'waiting'
  agents.dispatcher = 'waiting'
  lineStatus.readerToReviewer = false
  lineStatus.reviewerToCritic = false
}

// 暴露给父组件
defineExpose({ setAgentStatus, reset })

// --- UI 辅助计算函数 ---
const getNodeClass = (agent) => {
  const status = agents[agent]
  if (status === 'active') return 'border-blue-500 shadow-[0_0_15px_rgba(59,130,246,0.3)] bg-slate-800/80 transform scale-105'
  if (status === 'done') return 'border-emerald-500/50 bg-slate-900/60'
  if (status === 'error') return 'border-red-500/50 bg-red-900/20'
  return 'border-slate-700 bg-slate-900/40 opacity-70' // waiting
}

const getStatusText = (agent) => {
  const status = agents[agent]
  if (status === 'active') return 'Processing...'
  if (status === 'done') return 'Completed'
  if (status === 'error') return 'Failed'
  return 'Pending'
}

const getStatusTextColor = (agent) => {
  const status = agents[agent]
  if (status === 'active') return 'text-blue-400 font-bold animate-pulse'
  if (status === 'done') return 'text-emerald-500'
  if (status === 'error') return 'text-red-400'
  return 'text-slate-500'
}
</script>

<style scoped>
@reference "tailwindcss";

.agent-node {
  @apply flex items-center gap-4 px-5 py-3 rounded-xl border transition-all duration-500 relative;
  min-width: 180px;
}
.icon-box {
  @apply w-10 h-10 flex items-center justify-center rounded-lg text-xl border border-slate-700 shadow-inner;
}

/* 极其关键的 SVG 虚线流动动画 */
.animate-dash {
  animation: dashMove 1s linear infinite;
}
@keyframes dashMove {
  from { stroke-dashoffset: 12; }
  to { stroke-dashoffset: 0; }
}
</style>
